### ISSUE TITLE
Can't load module – hardcoded paths

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt-community/nuxt-logrocket#327]
```
Error while requiring module nuxt-logrocket: Error [ERR_MODULE_NOT_FOUND]: 
Cannot find module '/home/farzad/projects/oss/nuxt-logrocket/node_modules/jiti/lib/index.js'
imported from /Users/lukaszflorczak/my-project/node_modules/.pnpm/nuxt-logrocket@2.0.0_rollup@2.79.1/node_modules/nuxt-logrocket/dist/module.mjs
```

There are hardcoded paths In `module.d.ts`:
```js
export * from "/home/farzad/projects/oss/nuxt-logrocket/src/module";
export { default } from "/home/farzad/projects/oss/nuxt-logrocket/src/module";
```

and `module.mjs`:
```js
import jiti from "file:///home/farzad/projects/oss/nuxt-logrocket/node_modules/jiti/lib/index.js";

/** @type {import("/home/farzad/projects/oss/nuxt-logrocket/src/module")} */
const _module = jiti(null, { interopDefault: true, esmResolve: true })("/home/farzad/projects/oss/nuxt-logrocket/src/module.ts");

export default _module;
```

**Comment by farzadso** [comment]
Oh god. How has this happened? Which version are you using?

**Comment by lukaszflorczak** [comment]
`v2.0.0`

**Comment by dbhagen** [comment]
Yep, came here for this issue. I'll see if I can get you a PR if I have a minute.

**Comment by dbhagen** [comment]
Actually, looks like your code is fine, maybe just uploaded the wrong package to NPMJS?

**Comment by farzadso** [comment]
@lukaszflorczak @dbhagen Should be fixed in `v2.0.1`. Sorry for the inconvenience. Please let me know if it's fixed so I can close this issue.

**Comment by lukaszflorczak** [comment]
Now I have an error:
```
Failed to resolve import "/Users/lukaszflorczak/my-project/node_modules/.pnpm/nuxt-logrocket@2.0.1/node_modules/nuxt-logrocket/dist/runtime/plugin.client.ts" from "virtual:nuxt:/Users/lukaszflorczak/my-project/.nuxt/plugins/client.mjs". Does the file exist?
```

**Comment by trueter** [comment]
I'm using version 2.0.4 and can still see the hardcoded paths above.
Using nuxt 3.0.0, npm 8.19.3, node 19.1.0

**Comment by farzadso** [comment]
I'm still working on the issue. I don't know what's causing the hardcoded paths.

I'll update asap.

**Comment by blocka** [comment]
any updates? Is there a known good version?

**Comment by tt-david** [comment]
How to fix this temporarily?

**Comment by lukaszflorczak** [comment]
I downloaded the source code and added it to my project as locale module. And it works.

**Comment by hclj37** [comment]
Any progress? 😢

**Comment by JeremyMees** [comment]
@farzadso  Do you have a update on this?

**Comment by farzadso** [comment]
Sorry everyone for the inconvenience.  Should be fixed in `v2.0.5`. Please reopen if issue persists.
